include:
  - path: proxy.yaml

services:
  web:
    build:
      context: /opt/app
      network: host
      dockerfile: Dockerfile.python
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: app
      DB_NAME: virtd
      DB_PASSWORD: QwErTy1234
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 2
    networks:
      backend:
        ipv4_address: 172.20.0.10
