include:
  - path: proxy.yaml

services:
  web:
    image: cr.yandex/crp1c299naqueubq8k0r/shvirtd-example-python:0.0.1
    environment:
      DB_HOST: db
      DB_USER: app
      DB_NAME: virtd
      DB_PASSWORD: QwErTy1234
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    env_file: .env
    networks:
      backend:
        ipv4_address: 172.20.0.10
    
