#!/usr/bin/env bash

URL="https://github.com/vdrandom/shvirtd-example-python.git"
DEST=/opt/app

[[ -d "$DEST" ]] && rm -Rf "$DEST"
git clone "$URL" "$DEST"
docker compose -f "$DEST/compose.yaml" up -d
