#!/usr/bin/env bash

URL="https://github.com/vdrandom/shvirtd-example-python.git"
DEST=/opt/app
BRANCH=solution

[[ -d "$DEST" ]] && rm -Rf "$DEST"
git clone "$URL" "$DEST"
git -C "$DEST" checkout --track "origin/$BRANCH"
docker compose -f "$DEST/compose.yaml" build
docker compose -f "$DEST/compose.yaml" up -d
