---
- name: Do teh magics
  hosts: all
  become: true
  tasks:
    - name: Install necessary packages
      ansible.builtin.dnf:
        name:
         - yum-utils
         - git
        state: present

    - name: Set up docker repository
      ansible.builtin.command:
        argv:
          - yum-config-manager
          - --add-repo
          - https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Start and enable service
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - docker.socket

    - name: Copy deploy script
      ansible.builtin.copy:
        src: ../deploy
        dest: /opt/deploy
        mode: "0700"

    - name: Run deploy script
      ansible.builtin.command:
        argv:
          - /opt/deploy
